# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nando' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nando

  pod 'Google/SignIn'

  target 'nando-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nandoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'nando-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nando-tvOS

end
